stages:
  - build
  - test

build:
  stage: build
  image: openjdk:11-jdk
  allow_failure: false
  when: manual
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew
  cache:
    key: $CI_PROJECT_NAME
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script:
    ./gradlew assemble
  tags:
    - linux

test-linux:
  stage: test
  script:
    ./gradlew jvmTest